Save Image To Gallery
255BITS/hypr pull request #12
Opened 2017-07-19 19:37 UTC by TedHoryczun

2017-07-20 09:46 UTC, martyn requested changes
I had trouble loading the image into the emulator(it was located in /sdcard) so I couldn't test.

Found some small code issues.

2017-07-20 09:46 UTC, martyn commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
Looks like this is included twice

2017-07-20 09:46 UTC, martyn commented on app/src/main/java/hypr/a255bits/com/hypr/Util/ImageSaver.kt
> +        Log.i("LOAD", root + fname)
s/LOAD/SAVE ?

2017-07-20 09:46 UTC, martyn commented on app/src/main/java/hypr/a255bits/com/hypr/Util/ImageSaver.kt
> +            out.flush()
flush not needed

2017-07-20 09:46 UTC, martyn commented on app/src/main/java/hypr/a255bits/com/hypr/Util/ImageSaver.kt
> +        myDir.mkdirs()
root should already exist I think

2017-07-20 13:11 UTC, TedHoryczun commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
It's included twice because the app needs to be able to read from the storage to get an image. As well as write to the storage to save an image.

2017-07-24 14:52 UTC, mikkel approved these changes
Code LGTM 👍

2017-07-24 14:52 UTC, mikkel commented on app/src/main/java/hypr/a255bits/com/hypr/Util/ImageSaver.kt
> +        val fname = "/Image-$fileName.jpg"
Does the image name here matter?  Maybe we want to call it hypr-$fileName ?

2017-07-24 15:10 UTC, martyn approved these changes

2017-07-24 15:28 UTC, merged